Repository auchan-squid-game/auchan-squid-game, pull requests merged in 2021-11, with the labels that each got.

#45 creation of config files for enigmas
  src/enigmas.json
Labels: enhancement

#46 Response validation
  database.rules.json
  src/constants/mutation-types.js
  src/enigmas.json
  src/services/user-services.js
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/views/AdministationView/AdministationView.vue
  src/views/AdministationView/EnigmaSection.vue
Labels: enhancement

#34 Manage the application signin
  src/constants/mutation-types.js
  src/services/user-services.js
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/views/AuthenticationView/Login.vue
Labels: enhancement

#50 Ranking page
  src/constants/mutation-types.js
  src/services/user-services.js
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/views/RankingView/RankingView.vue
Labels: enhancement

#28 Implement CD
  .github/workflows/build-actions.yml
  index.js
Labels: chore

#51 Create the enigma page
  src/dev-enigmas.json
  src/services/user-services.js
  src/store/actions.js
  src/store/mutations.js
  src/views/AdministationView/AdministationView.vue
  src/views/AdministationView/EnigmaSection.vue
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: enhancement

#60 GitHub actions not running anymore on commit push
  .github/workflows/build-actions.yml
  .github/workflows/deploy.yml
Labels: bug

#58 Add answer control in enigma popup
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: bug

#56 Ignore admin in ranking
  src/store/actions.js
Labels: enhancement

#62 Passer l'intitulé des tags d'approbation de réponse en français.
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: enhancement

#69 correction of start date with gmt+1
  src/views/EnigmaPopup/EnigmaPopup.vue
  src/views/HomepageView/Calendar/CalendarCell.vue
Labels: bug

#68 correction of bug when open enigma popup
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: bug

#70 correction of the response field always displayed
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: bug

#72 Fix/71 correction of end date of enigma
  src/dev-enigmas.json
  src/enigmas.json
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: bug

#73 Make website more responsive
  src/layout/Header.vue
  src/views/AuthenticationView/AuthentificationForm/index.vue
  src/views/HomepageView/Calendar/index.vue
  src/views/HomepageView/HomepageView.vue
  src/views/LaunchCountdownView/LaunchCountdownView.vue
  src/views/RankingView/RankingView.vue
Labels: ui/ux

#74 Reset the answer on close
  src/constants/mutation-types.js
  src/store/actions.js
  src/store/mutations.js
  src/views/EnigmaPopup/EnigmaPopup.vue
Labels: bug

#76 Update favicon
  public/favicon.ico
Labels: enhancement
